### PR TITLE
Fixed bug in common.inc.php line 1168

### PR DESCRIPTION
**Pull request by Newman101**
Good morning. There was a bug in your common.inc.php file. 

Let me explain the situation. Original common.inc.php had this file path:

./language//text.php

I removed the extra slash so that path became:

./language/text.php

There are no custom languages in this repo yet, but that might have caused a bit of an issue.

I hope this helps. :)

### CODE REVIEW

**Comment by mkoch227** [comment]
I'm looking at the default HESK 2.6.0 beta 1's `common.inc.php` file, and the code block is

````php
require(HESK_PATH . 'language/' . $hesk_settings['languages'][$hesk_settings['language']]['folder'] . '/text.php');

Additionally, looking at the `$hesk_settings['language']` array in `hesk_settings.inc.php`, the default / English language is added as follows

````php
$hesk_settings['languages']=array(
'English' => array('folder'=>'en','hr'=>'------ Reply above this line ------'),
);

If we take the english array, and update the `common.inc.php` file with this information, we get:
````php
require(HESK_PATH . 'language/en/text.php');

Since `$hesk_settings['language']` is `English`, and `$hesk_settings['languages']['English']['folder']` is 'en', with no leading or trailing slashes. 

So, the code is correct as-is (otherwise the language file would be failing for everyone right now).  Are you having an issue with a non-English language that required you to make this change?

**Comment by Newman101** [comment]
Ah, got it. I was thinking about creating a Finnish language file, tested the software and could not get it working. Index.php gave a white screen after cloning the repo. Had to investigate it a bit and I thought this was actually a bug.

**Comment by mkoch227** [comment]
Gotcha. I'll close out this PR then.

**Comment by Newman101** [comment]
Ok, cheers. :)

**Pull request closed without merging**
